"""Nuevas tablas

Revision ID: 67d0970cea95
Revises: 30537d71c419
Create Date: 2020-11-27 00:26:02.303930

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '67d0970cea95'
down_revision = '30537d71c419'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('Categoria',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('nombre', sa.String(length=50), nullable=False),
    # sa.Column('descripcion', sa.String(length=100), nullable=True),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_table('Medida',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('nombre', sa.String(length=50), nullable=False),
    # sa.Column('proporcion', sa.Float(), nullable=False),
    # sa.PrimaryKeyConstraint('id')
    # )
    op.create_table('Ingrediente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=100), nullable=True),
    sa.Column('precio', sa.Float(), nullable=True),
    sa.Column('medida_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['medida_id'], ['Medida.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Receta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('precio_venta', sa.Float(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['Categoria.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # op.drop_table('categoria')
    # op.drop_table('medida')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medida',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(collation='latin1_spanish_ci', length=50), nullable=False),
    sa.Column('proporcion', mysql.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='latin1_spanish_ci',
    mysql_default_charset='latin1',
    mysql_engine='MyISAM'
    )
    op.create_table('categoria',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(collation='latin1_spanish_ci', length=50), nullable=False),
    sa.Column('descripcion', mysql.VARCHAR(collation='latin1_spanish_ci', length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='latin1_spanish_ci',
    mysql_default_charset='latin1',
    mysql_engine='MyISAM'
    )
    op.drop_table('Receta')
    op.drop_table('Ingrediente')
    op.drop_table('Medida')
    op.drop_table('Categoria')
    # ### end Alembic commands ###
