"""empty message

Revision ID: bdf126688aba
Revises: d92dce4a319c
Create Date: 2021-09-20 11:16:56.597209

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bdf126688aba'
down_revision = 'd92dce4a319c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Receta', 'costo',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('Receta', 'ganancia',
               existing_type=mysql.FLOAT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Receta', 'ganancia',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('Receta', 'costo',
               existing_type=mysql.FLOAT(),
               nullable=True)
    # ### end Alembic commands ###
