"""empty message

Revision ID: d92dce4a319c
Revises: 281dcaed17d4
Create Date: 2021-09-19 10:55:07.562825

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd92dce4a319c'
down_revision = '281dcaed17d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Ingrediente_ibfk_1', 'Ingrediente', type_='foreignkey')
    op.create_foreign_key(None, 'Ingrediente', 'Medida', ['medida_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('IngredienteReceta_ibfk_3', 'IngredienteReceta', type_='foreignkey')
    op.drop_constraint('IngredienteReceta_ibfk_1', 'IngredienteReceta', type_='foreignkey')
    op.drop_constraint('IngredienteReceta_ibfk_2', 'IngredienteReceta', type_='foreignkey')
    op.create_foreign_key(None, 'IngredienteReceta', 'Receta', ['receta_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'IngredienteReceta', 'Ingrediente', ['ingrediente_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'IngredienteReceta', 'Medida', ['medida_id'], ['id'], ondelete='CASCADE')
    op.add_column('Receta', sa.Column('costo', sa.Float(), nullable=True))
    op.add_column('Receta', sa.Column('ganancia', sa.Float(), nullable=True))
    op.drop_constraint('Receta_ibfk_1', 'Receta', type_='foreignkey')
    op.create_foreign_key(None, 'Receta', 'Categoria', ['categoria_id'], ['id'], ondelete='CASCADE')
    op.drop_column('Receta', 'precio_venta')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Receta', sa.Column('precio_venta', mysql.FLOAT(), nullable=True))
    op.drop_constraint(None, 'Receta', type_='foreignkey')
    op.create_foreign_key('Receta_ibfk_1', 'Receta', 'Categoria', ['categoria_id'], ['id'])
    op.drop_column('Receta', 'ganancia')
    op.drop_column('Receta', 'costo')
    op.drop_constraint(None, 'IngredienteReceta', type_='foreignkey')
    op.drop_constraint(None, 'IngredienteReceta', type_='foreignkey')
    op.drop_constraint(None, 'IngredienteReceta', type_='foreignkey')
    op.create_foreign_key('IngredienteReceta_ibfk_2', 'IngredienteReceta', 'Medida', ['medida_id'], ['id'])
    op.create_foreign_key('IngredienteReceta_ibfk_1', 'IngredienteReceta', 'Ingrediente', ['ingrediente_id'], ['id'])
    op.create_foreign_key('IngredienteReceta_ibfk_3', 'IngredienteReceta', 'Receta', ['receta_id'], ['id'])
    op.drop_constraint(None, 'Ingrediente', type_='foreignkey')
    op.create_foreign_key('Ingrediente_ibfk_1', 'Ingrediente', 'Medida', ['medida_id'], ['id'])
    # ### end Alembic commands ###
